package com.example.sgs_backend.domain.user;

public enum PermissionName {
    PRODUCT_READ, PRODUCT_CREATE, PRODUCT_UPDATE, PRODUCT_DELETE, PRODUCT_IMPORT, PRODUCT_EXPORT,
    STOCK_READ, STOCK_ENTRY, STOCK_EXIT, STOCK_TRANSFER, STOCK_ADJUST, STOCK_INVENTORY,
    EXPENSE_READ, EXPENSE_CREATE, EXPENSE_UPDATE, EXPENSE_APPROVE, EXPENSE_REJECT, EXPENSE_EXPORT,
    PURCHASE_ORDER_READ, PURCHASE_ORDER_CREATE, PURCHASE_ORDER_RECEIVE, PURCHASE_ORDER_CANCEL,
    SALE_ORDER_READ, SALE_ORDER_CREATE, INVOICE_READ, INVOICE_CREATE, INVOICE_SEND,
    CUSTOMER_READ, CUSTOMER_CREATE, CUSTOMER_UPDATE,
    REPORT_STOCK, REPORT_FINANCIAL, REPORT_EXPENSE, REPORT_SALES,
    USER_READ, USER_CREATE, USER_UPDATE, USER_DELETE,
    ROLE_MANAGE, SITE_MANAGE, CONFIG_MANAGE, AUDIT_LOG_READ
}
